### ISSUE TITLE
GitHub Actions CI - Fix Bundler Cache Issue - Exit Code 16

### ISSUE THREAD

**Issue by curtisspendlove** [knightoftheoldcode/jekyll-theme-squire#11]
When using `bundler-cache: true` in `ci.yml` for GitHub Actions, execution fails with "exit code 16" (processor architecture mismatch?)

```yaml
- name: Set Up Ruby 3.2
  uses: ruby/setup-ruby@v1
  with:
    ruby-version: 3.2
    bundler-cache: false
```

`Error: The process '/opt/hostedtoolcache/Ruby/3.2.2/x64/bin/bundle' failed with exit code 16`

![image](https://github.com/knightoftheoldcode/jekyll-theme-squire/assets/11726017/4b6bf146-288b-4e21-8164-ea7760c82b9c)
